2020-04-28 14:46:54,982 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 16:30:38,216 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 16:31:47,997 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 16:34:12,649 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 16:34:40,516 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 17:49:07,091 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 17:49:49,636 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-29 17:50:44,641 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-30 19:46:01,622 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-30 20:42:02,536 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:45]
2020-04-30 21:05:28,629 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:47]
2020-04-30 21:11:25,897 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:47]
2020-04-30 21:14:41,496 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:47]
2020-05-01 17:30:49,702 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:47]
2020-05-01 17:31:32,039 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:47]
2020-05-01 18:17:20,596 ERROR: Exception on /register [GET] [in e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\WEB\python_section\microblog_megabook\app\routes.py", line 114, in register
    return render_template('register.html', title='Register', form=form)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\WEB\python_section\microblog_megabook\app\templates\register.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2020-05-01 18:17:53,233 ERROR: Exception on /register [GET] [in e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\WEB\python_section\microblog_megabook\app\routes.py", line 114, in register
    return render_template('register.html', title='Register', form=form)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\WEB\python_section\microblog_megabook\app\templates\register.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2020-05-01 18:19:38,779 ERROR: Exception on /register [GET] [in e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\WEB\python_section\microblog_megabook\app\routes.py", line 114, in register
    return render_template('register.html', title='Register', form=form)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\WEB\python_section\microblog_megabook\app\templates\register.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "e:\web\python_section\microblog_megabook\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2020-05-02 14:38:55,818 INFO: Microblog startup [in E:\WEB\python_section\microblog_megabook\app\__init__.py:49]
